SET(LINUX_WORKSPACE /home/ice/thesis)
SET(WINDOWS_WORKSPACE D:/thesis)

IF(CMAKE_HOST_SYSTEM_NAME MATCHES Linux)
    SET(WORKSPACE ${LINUX_WORKSPACE} CACHE PATH "")
ELSE()
    SET(WORKSPACE ${WINDOWS_WORKSPACE} CACHE PATH "")
ENDIF()

SET(ANDROID_NDK /opt/android-ndk-r10ae CACHE PATH "")
SET(ANDROID_CMAKE_PATH ${WORKSPACE}/repositories/scripts/android-cmake CACHE PATH "")

SET(CMAKE_INSTALL_PREFIX ${WORKSPACE}/dist CACHE PATH "")
SET(HEADER_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/inc CACHE PATH "")
SET(LIBRARY_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/lib CACHE PATH "")

#SET(ASIO_LIBRARY_PATH ${WORKSPACE}/libraries/asio-1.10.6/include)
#SET(WEBSOCKETPP_LIBRARY_PATH ${WORKSPACE}/libraries/websocketpp)
