
function(set_common_defines)
    if(NOT DEFINED CMAKE_BUILD_TYPE)
        SET(CMAKE_BUILD_TYPE Debug CACHE STRING "")
    endif()

    SET(LINUX_WORKSPACE /home/ice/thesis)
    SET(WINDOWS_WORKSPACE D:/thesis)

    IF(CMAKE_HOST_SYSTEM_NAME MATCHES Linux)
        SET(WORKSPACE ${LINUX_WORKSPACE} CACHE PATH "")
    ELSE()
        SET(WORKSPACE ${WINDOWS_WORKSPACE} CACHE PATH "")
    ENDIF()

    SET(ANDROID_NDK /opt/android-ndk-r10e CACHE PATH "")
    SET(ANDROID_CMAKE_PATH ${WORKSPACE}/repositories/scripts/android-cmake CACHE PATH "")

endfunction(set_common_defines)


function(set_paths)
    SET(CMAKE_INSTALL_PREFIX ${WORKSPACE}/dist CACHE PATH "" FORCE)
    SET(HEADER_INSTALL_DIR inc CACHE PATH "")

    IF(TARGET_SYSTEM MATCHES Android)
        SET(LIBRARY_INSTALL_DIR lib/${CMAKE_BUILD_TYPE}/${TARGET_SYSTEM}/${ANDROID_NATIVE_API_LEVEL}/${ANDROID_ABI} CACHE PATH "" FORCE)
    ELSE()
        SET(LIBRARY_INSTALL_DIR lib/${CMAKE_BUILD_TYPE}/${TARGET_SYSTEM} CACHE PATH "" FORCE)
    ENDIF()

    SET(LIBRARY_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/${LIBRARY_INSTALL_DIR} CACHE PATH "" FORCE)
    SET(HEADERS_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/${HEADER_INSTALL_DIR} CACHE PATH "")

    #SET(ASIO_LIBRARY_PATH ${WORKSPACE}/libraries/asio-1.10.6/include)
    #SET(WEBSOCKETPP_LIBRARY_PATH ${WORKSPACE}/libraries/websocketpp)
endfunction(set_paths)

function(setup_libwebsockets)
    SET(LWS_WITH_SSL OFF CACHE BOOL "")

    SET(LWS_WITHOUT_TESTAPPS ON CACHE BOOL "")
    SET(LWS_WITHOUT_TEST_SERVER ON CACHE BOOL "")
    SET(LWS_WITHOUT_TEST_SERVER_EXTPOLL ON CACHE BOOL "")
    SET(LWS_WITHOUT_TEST_PING ON CACHE BOOL "")
    SET(LWS_WITHOUT_TEST_CLIENT ON CACHE BOOL "")
    SET(LWS_WITHOUT_TEST_FRAGGLE ON CACHE BOOL "")

    IF(CMAKE_BUILD_TYPE MATCHES Debug)
        SET(LWS_WITHOUT_DEBUG OF CACHE BOOL "" FORCE)
    ELSE()
        SET(LWS_WITHOUT_DEBUG ON CACHE BOOL "" FORCE)
    ENDIF()

    SET(LWS_INSTALL_INCLUDE_DIR ${HEADER_INSTALL_DIR} CACHE PATH "")
    SET(LWS_INSTALL_LIB_DIR ${LIBRARY_INSTALL_DIR} CACHE PATH "" FORCE)
    SET(LWS_INSTALL_CMAKE_DIR ${PROJECT_BINARY_DIR} CACHE PATH "")

endfunction(setup_libwebsockets)
