
SET(LWS_WITH_SSL OFF CACHE BOOL "")

SET(LWS_WITHOUT_TESTAPPS ON CACHE BOOL "")
SET(LWS_WITHOUT_TEST_SERVER ON CACHE BOOL "")
SET(LWS_WITHOUT_TEST_SERVER_EXTPOLL ON CACHE BOOL "")
SET(LWS_WITHOUT_TEST_PING ON CACHE BOOL "")
SET(LWS_WITHOUT_TEST_CLIENT ON CACHE BOOL "")
SET(LWS_WITHOUT_TEST_FRAGGLE ON CACHE BOOL "")
SET(LWS_INSTALL_INCLUDE_DIR inc CACHE PATH "")

IF(CMAKE_BUILD_TYPE MATCHES Debug)
    SET(LWS_WITHOUT_DEBUG OF CACHE BOOL "")
ELSE()
    SET(LWS_WITHOUT_DEBUG ON CACHE BOOL "")
ENDIF()

IF(CMAKE_SYSTEM_NAME MATCHES Android)
    SET(LWS_INSTALL_LIB_DIR lib/${CMAKE_BUILD_TYPE}/${CMAKE_SYSTEM_NAME}/${ANDROID_NATIVE_API_LEVEL}/${ANDROID_ABI} CACHE PATH "")
ELSE()
    SET(LWS_INSTALL_LIB_DIR lib/${CMAKE_BUILD_TYPE}/${CMAKE_SYSTEM_NAME} CACHE PATH "")
ENDIF()

SET(LWS_INSTALL_CMAKE_DIR ${PROJECT_BINARY_DIR} CACHE PATH "")
