
SET(LWS_WITH_SSL OFF CACHE BOOL "")

SET(LWS_WITHOUT_TESTAPPS ON CACHE BOOL "")
SET(LWS_WITHOUT_TEST_SERVER ON CACHE BOOL "")
SET(LWS_WITHOUT_TEST_SERVER_EXTPOLL ON CACHE BOOL "")
SET(LWS_WITHOUT_TEST_PING ON CACHE BOOL "")
SET(LWS_WITHOUT_TEST_CLIENT ON CACHE BOOL "")
SET(LWS_WITHOUT_TEST_FRAGGLE ON CACHE BOOL "")
SET(LWS_INSTALL_INCLUDE_DIR inc CACHE PATH "")

IF(CMAKE_BUILD_TYPE MATCHES Debug)
    SET(LWS_WITHOUT_DEBUG OF CACHE BOOL "")
ELSE()
    SET(LWS_WITHOUT_DEBUG ON CACHE BOOL "")
ENDIF()
