
function(set_common_defines)

    SET(WORKSPACE "$ENV{WORKSPACE}")
    IF (NOT WORKSPACE)
        IF(CMAKE_HOST_SYSTEM_NAME MATCHES Linux)
            SET(WORKSPACE "/home/ice/thesis" CACHE PATH "")
        ELSE()
            SET(WORKSPACE "D:/thesis" CACHE PATH "")
        ENDIF()
    ENDIF()
    MESSAGE(STATUS "WORKSPACE:" ${WORKSPACE})


    if(NOT CMAKE_BUILD_TYPE)
        SET(CMAKE_BUILD_TYPE "Debug" CACHE STRING "" FORCE)
    endif()
    MESSAGE(STATUS "CMAKE_BUILD_TYPE:" ${CMAKE_BUILD_TYPE})

    IF (CMAKE_SYSTEM_NAME MATCHES Android)
        SET(ANDROID_NDK "$ENV{ANDROID_NDK}")
        IF (NOT ANDROID_NDK)
            IF(CMAKE_HOST_SYSTEM_NAME MATCHES Linux)
                SET(ANDROID_NDK "/opt/android-ndk-r10e" CACHE PATH "")
            ELSE()
                SET(ANDROID_NDK "C:/android-ndk-r10e" CACHE PATH "")
            ENDIF()
        ENDIF()
        MESSAGE(STATUS "ANDROID_NDK:" ${ANDROID_NDK})

        SET(ANDROID_CMAKE_PATH "${WORKSPACE}/repositories/scripts/android-cmake" CACHE PATH "")
        MESSAGE(STATUS "ANDROID_CMAKE_PATH:" ${ANDROID_CMAKE_PATH})
    ENDIF()
endfunction()


function(set_paths)
    SET(CMAKE_INSTALL_PREFIX "${WORKSPACE}/dist" CACHE PATH "")
    SET(HEADERS_INSTALL_DIR inc CACHE PATH "")

    IF(CMAKE_SYSTEM_NAME MATCHES Android)
        SET(LIBRARY_INSTALL_DIR lib/${CMAKE_BUILD_TYPE}/${CMAKE_SYSTEM_NAME}/${ANDROID_NATIVE_API_LEVEL}/${ANDROID_ABI} CACHE PATH "")
    ELSE()
        SET(LIBRARY_INSTALL_DIR lib/${CMAKE_BUILD_TYPE}/${CMAKE_SYSTEM_NAME} CACHE PATH "")
    ENDIF()

    SET(LIBRARY_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/${LIBRARY_INSTALL_DIR} CACHE PATH "")
    SET(HEADERS_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/${HEADERS_INSTALL_DIR} CACHE PATH "")

    MESSAGE(STATUS "HEADERS_INSTALL_PATH:" ${HEADERS_INSTALL_PATH})
    MESSAGE(STATUS "LIBRARY_INSTALL_PATH:" ${LIBRARY_INSTALL_PATH})

    #SET(ASIO_LIBRARY_PATH ${WORKSPACE}/libraries/asio-1.10.6/include)
    #SET(WEBSOCKETPP_LIBRARY_PATH ${WORKSPACE}/libraries/websocketpp)
endfunction()

function(setup_libwebsockets)
    SET(LWS_WITH_SSL OFF CACHE BOOL "")

    SET(LWS_WITHOUT_TESTAPPS ON CACHE BOOL "")
    SET(LWS_WITHOUT_TEST_SERVER ON CACHE BOOL "")
    SET(LWS_WITHOUT_TEST_SERVER_EXTPOLL ON CACHE BOOL "")
    SET(LWS_WITHOUT_TEST_PING ON CACHE BOOL "")
    SET(LWS_WITHOUT_TEST_CLIENT ON CACHE BOOL "")
    SET(LWS_WITHOUT_TEST_FRAGGLE ON CACHE BOOL "")
    SET(LWS_IPV6 OF CACHE BOOL "")

    IF(CMAKE_BUILD_TYPE MATCHES Debug)
        SET(LWS_WITHOUT_DEBUG OF CACHE BOOL "")
    ELSE()
        SET(LWS_WITHOUT_DEBUG ON CACHE BOOL "")
    ENDIF()

    SET(LWS_INSTALL_INCLUDE_DIR ${HEADERS_INSTALL_DIR} CACHE PATH "")
    SET(LWS_INSTALL_LIB_DIR ${LIBRARY_INSTALL_DIR} CACHE PATH "" FORCE)
    SET(LWS_INSTALL_BIN_DIR ${LWS_INSTALL_LIB_DIR} CACHE PATH "" FORCE)
    SET(LWS_INSTALL_CMAKE_DIR ${PROJECT_BINARY_DIR} CACHE PATH "")

endfunction()
